# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f7ca3ce64a6221ce1793b4c987ce8e6e26a5d48053b409531f0e00d53a12c5e82d301ef04e2b04aed30f3a89069c75b9a7072b77a142c703848d7157fa53ee7

test:
  secret_key_base: 1c482c0ea9bd381c2705f7524b339b74e6904d34c6d53453a8568e3d145e422fbe06d563faf1b761ac95603c22d807730b4351f052114ab9f6dbdf1678fc0f74

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
